version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  ml_client:
    build:
      context: .
      dockerfile: Dockerfile.ml_client
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=MLAPP
    depends_on:
      - mongodb

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.web-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=MLAPP
    depends_on:
      - mongodb
