name: check lint and format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          find . -name "*.py" ! -path "./machine-learning-client/tests/*" ! -path "./web-app/tests/*" | xargs pipenv run pylint --ignored-modules=cv2
      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run black --diff --check . --exclude "machine-learning-client/tests/*" --exclude "web-app/tests/*"
