name: Web App CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web-app/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MONGO_URI: "mongodb://mongodb:27017"
      MONGO_DBNAME: "MLAPP"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-flask pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd web-app
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and coverage
      run: |
        PYTHONPATH=./web-app pytest --cov=web-app --cov-report term-missing --cov-fail-under=80 tests/test_app.py
