name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     # python -m unittest discover -s web-app/tests
